[tool.poetry]
name = "flockwave-gps"
version = "2.3.3"
description = "GPS and geography related routines and classes"
authors = ["Tamas Nepusz <tamas@collmot.com>"]
packages = [
    { include = "flockwave", from = "src" }
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
trio = {version = "^0.22.0", optional = true}
bitstring = "^4.0.1"
pynmea2 = "^1.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
coverage = {extras = ["toml"], version = "^7.2.1"}
pytest-cov = "^4.0.0"

[tool.poetry.extras]
ntrip = ["trio"]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"
priority = "explicit"

[[tool.poetry.source]]
name = "fury"
url = "https://pypi.fury.io/skybrush/"
priority = "supplemental"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
